#!/usr/bin/env python3
"""
AI Chatbot Setup Script for Fitness Club Management System
This script helps you configure the AI chatbot with your preferred provider and API keys.
"""

import os
import sys
from pathlib import Path

def create_env_file():
    """Create or update the config.env file"""
    env_file = Path("config.env")
    
    print("🤖 AI Chatbot Setup for Fitness Club Management System")
    print("=" * 60)
    
    # Check if config.env already exists
    if env_file.exists():
        print("📁 Found existing config.env file")
        response = input("Do you want to overwrite it? (y/N): ").lower()
        if response != 'y':
            print("Setup cancelled. Existing config.env preserved.")
            return
    
    print("\n🔑 Let's configure your AI chatbot provider...")
    
    # Provider selection
    print("\nAvailable AI providers:")
    print("1. Groq (Fast, cost-effective)")
    print("2. Ollama (Local, free, requires local setup)")
    print("3. OpenAI (High quality, paid)")
    
    while True:
        try:
            choice = input("\nSelect your preferred provider (1-3): ").strip()
            if choice in ['1', '2', '3']:
                break
            print("Please enter 1, 2, or 3")
        except KeyboardInterrupt:
            print("\nSetup cancelled.")
            return
    
    providers = {
        '1': 'groq',
        '2': 'ollama', 
        '3': 'openai'
    }
    
    selected_provider = providers[choice]
    
    # Collect configuration
    config = {
        'CHATBOT_PROVIDER': selected_provider,
        'MAX_TOKENS': '1000',
        'TEMPERATURE': '0.7'
    }
    
    # Provider-specific configuration
    if selected_provider == 'groq':
        print("\n🔑 Groq Configuration:")
        print("Get your API key from: https://console.groq.com/")
        groq_key = input("Enter your Groq API key: ").strip()
        if groq_key:
            config['GROQ_API_KEY'] = groq_key
        config['OPENAI_API_KEY'] = ''
        config['OLLAMA_BASE_URL'] = 'http://localhost:11434'
        config['OLLAMA_MODEL'] = 'llama3.2:3b'
        
    elif selected_provider == 'ollama':
        print("\n🖥️  Ollama Configuration:")
        print("Make sure Ollama is installed and running locally")
        print("Install from: https://ollama.ai/")
        
        ollama_url = input("Ollama base URL (default: http://localhost:11434): ").strip()
        if ollama_url:
            config['OLLAMA_BASE_URL'] = ollama_url
        else:
            config['OLLAMA_BASE_URL'] = 'http://localhost:11434'
            
        ollama_model = input("Ollama model (default: llama3.2:3b): ").strip()
        if ollama_model:
            config['OLLAMA_MODEL'] = ollama_model
        else:
            config['OLLAMA_MODEL'] = 'llama3.2:3b'
            
        config['GROQ_API_KEY'] = ''
        config['OPENAI_API_KEY'] = ''
        
    elif selected_provider == 'openai':
        print("\n🔑 OpenAI Configuration:")
        print("Get your API key from: https://platform.openai.com/api-keys")
        openai_key = input("Enter your OpenAI API key: ").strip()
        if openai_key:
            config['OPENAI_API_KEY'] = openai_key
        config['GROQ_API_KEY'] = ''
        config['OLLAMA_BASE_URL'] = 'http://localhost:11434'
        config['OLLAMA_MODEL'] = 'llama3.2:3b'
    
    # Write config file
    try:
        with open(env_file, 'w') as f:
            f.write("# AI Chatbot Configuration\n")
            f.write(f"# Generated by setup script\n\n")
            
            for key, value in config.items():
                f.write(f"{key}={value}\n")
        
        print(f"\n✅ Configuration saved to {env_file}")
        print(f"🤖 AI Chatbot configured to use: {selected_provider.upper()}")
        
        if selected_provider == 'ollama':
            print("\n📋 Next steps for Ollama:")
            print("1. Install Ollama: https://ollama.ai/")
            print("2. Run: ollama pull llama3.2:3b")
            print("3. Start Ollama service")
            
        print("\n🚀 You can now run your Flask app and access the chatbot at /chat")
        
    except Exception as e:
        print(f"❌ Error creating config file: {e}")
        return

def check_dependencies():
    """Check if required packages are installed"""
    print("\n📦 Checking dependencies...")
    
    required_packages = ['flask', 'requests']
    missing_packages = []
    
    for package in required_packages:
        try:
            __import__(package)
            print(f"✅ {package}")
        except ImportError:
            print(f"❌ {package} (missing)")
            missing_packages.append(package)
    
    if missing_packages:
        print(f"\n⚠️  Missing packages: {', '.join(missing_packages)}")
        print("Install them with: pip install -r requirements.txt")
        return False
    
    return True

def main():
    """Main setup function"""
    try:
        if not check_dependencies():
            print("\n❌ Please install missing dependencies first.")
            return
        
        create_env_file()
        
    except KeyboardInterrupt:
        print("\n\nSetup cancelled by user.")
    except Exception as e:
        print(f"\n❌ Setup failed: {e}")

if __name__ == "__main__":
    main() 